### ISSUE TITLE
[Backend] Download files in the jupyterlab local storage

### ISSUE THREAD

**Issue by Soap2G** [vre-hub/zenodo-jupyterlab-extension#43]
At the moment listing files does not come with a clickable link for download.

We planned the following upgrades
```[tasklist]
### Tasks
- [ ] List files only with their names and not with the full path.
- [ ] Attach a link to the filenames.
- [ ] On click, trigger download of file NOT in the PC local storage, but in the Jupyterlab session's storage.
```
The standard path for the download can be `/home/zenodo`, or something along these lines.
