### ISSUE TITLE
[Frontend] Cosmetic improvements

### ISSUE THREAD

**Issue by Soap2G** [vre-hub/zenodo-jupyterlab-extension#44]
```[tasklist]
### Tasks
- [x] Make record listing responsive (i.e. remove the horizontal scrolling)
- [x] Format records to contain title, authors, description and files presented clearly, possibly reproducing what happens in the Zenodo webpage.
- [x] Switch order of Search <-> Login buttons
- [ ] Shrink columns width of Resource Type and Date Published -> Either make "Reseource Type" and "Date publish" become two lines, either just show "Resource" and "Date"
```

**Comment by garciagenrique** [comment]
@mrzengel can this issue be closed ?

**Comment by mrzengel** [comment]
Yes

**Comment by garciagenrique** [comment]
Right, thanks @mrzengel 

![image](https://github.com/user-attachments/assets/a6a142cf-dd61-452d-b7a3-8a8ba78ff07f)
